name: Merge Files Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge files into combined_output.php
      run: |
        # Tạo file đầu ra
        > combined_output.php
        
        # Gộp file đầu tiên (giữ <?php)
        echo "// Start of file: index.php" >> combined_output.php
        cat index.php | sed 's/\s*\<\?>\s*$//' >> combined_output.php
        echo "// End of file: index.php" >> combined_output.php
        echo "" >> combined_output.php
        
        # Gộp các file còn lại (loại bỏ <?php thừa)
        for file in load-tool.php api-helper.php nft-holders.php export-holders.php nft-holders-list.php tools.css tools.js; do
          if [ -f "$file" ]; then
            echo "// Start of file: $file" >> combined_output.php
            sed '1{/<\?php/d};s/\s*\<\?>\s*$//' "$file" >> combined_output.php
            echo "// End of file: $file" >> combined_output.php
            echo "" >> combined_output.php
          else
            echo "File $file does not exist!" >> combined_output.php
          fi
        done
        
        # Đảm bảo không có dòng trống thừa hoặc BOM
        sed -i '/^[[:space:]]*$/d' combined_output.php
        sed -i '1s/^\xEF\xBB\xBF//' combined_output.php

    - name: Commit and push combined file
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"
        git add combined_output.php
        git commit -m "Automatically merge files into combined_output.php"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
