name: Merge Files Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge files into combined_output.php
      run: |
        # Create output file in tools directory
        mkdir -p tools
        echo "" > tools/combined_output.php
        
        # Merge first file (keep <?php)
        if [ -f "index.php" ]; then
          echo "// Start of file: index.php" >> tools/combined_output.php
          cat index.php | sed 's/\s*\<\?>\s*$//' >> tools/combined_output.php
          echo "// End of file: index.php" >> tools/combined_output.php
          echo "" >> tools/combined_output.php
        else
          echo "index.php not found!" >> tools/combined_output.php
        fi
        
        # Merge remaining files (remove <?php if present)
        for file in load-tool.php api-helper.php nft-holders.php export-holders.php nft-holders-list.php tools.css tools.js; do
          if [ -f "$file" ]; then
            echo "// Start of file: $file" >> tools/combined_output.php
            sed '1{/<\?php/d};s/\s*\<\?>\s*$//' "$file" >> tools/combined_output.php
            echo "// End of file: $file" >> tools/combined_output.php
            echo "" >> tools/combined_output.php
          else
            echo "File $file not found!" >> tools/combined_output.php
          fi
        done
        
        # Clean up empty lines and BOM
        sed -i '/^[[:space:]]*$/d' tools/combined_output.php
        sed -i '1s/^\xEF\xBB\xBF//' tools/combined_output.php

    - name: Debug file content
      run: cat tools/combined_output.php || echo "File not created"

    - name: Commit and push combined file
      run: |
        git config --global user.name "VinaNetwork"
        git config --global user.email "your.email@example.com" # Thay bằng email GitHub của bạn
        git add tools/combined_output.php
        git commit -m "Automatically merge files into tools/combined_output.php" || echo "No changes, skipping commit"
        git push --force # Force push to ensure file is updated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
